[versions]
opendcs = "7.0.11"

jetty = "9.4.53.v20231009"
jetty-jsp = "9.2.30.v20200428"
javax-servlet-jsp = "2.3.0"
tomcat-embed = "9.0.84"
servlet-api = "4.0.1"
slf4j = "2.0.10"
jersey = "2.40"
postgresql = "42.7.1"
swagger = "2.2.19"
glassfish-jaxb = "2.3.3"
websocket = "1.1"
javax-validation = "2.0.1.Final"
#Test Dependencies
junit = "5.10.1"
mockito = "3.12.4"

[libraries]
opendcs = { module = "org.opendcs:opendcs", version.ref = "opendcs" }
jetty-jsp = { module = "org.eclipse.jetty:jetty-jsp", version.ref = "jetty-jsp" }
jetty-annotations = { module = "org.eclipse.jetty:jetty-annotations", version.ref = "jetty" }
jetty-server = { module = "org.eclipse.jetty:jetty-server", version.ref = "jetty" }
jetty-servlets = { module = "org.eclipse.jetty:jetty-servlets", version.ref = "jetty" }
jetty-servlet = { module = "org.eclipse.jetty:jetty-servlet", version.ref = "jetty" }
jetty-webapp = { module = "org.eclipse.jetty:jetty-webapp", version.ref = "jetty" }
tomcat-embed = { module = "org.apache.tomcat.embed:tomcat-embed-jasper", version.ref = "tomcat-embed" }

javax-validation = { module = "javax.validation:validation-api", version.ref = "javax-validation" }

javax-servlet-jsp = { module = "javax.servlet.jsp:javax.servlet.jsp-api", version.ref= "javax-servlet-jsp" }
servlet-api = { module = "javax.servlet:javax.servlet-api", version.ref = "servlet-api" }
slf4j-jdk = { module = "org.slf4j:slf4j-jdk14", version.ref = "slf4j" }

json-jackson = { module = "org.glassfish.jersey.media:jersey-media-json-jackson", version.ref = "jersey" }
jersey-container-servlet = { module = "org.glassfish.jersey.containers:jersey-container-servlet", version.ref = "jersey" }
jersey-hk2 = { module = "org.glassfish.jersey.inject:jersey-hk2", version.ref = "jersey" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
swagger-jaxrs2 = { module = "io.swagger.core.v3:swagger-jaxrs2-jakarta", version.ref = "swagger" }
jaxb-runtime = { module = "org.glassfish.jaxb:jaxb-runtime", version.ref = "glassfish-jaxb" }
websocket = { module = "javax.websocket:javax.websocket-api", version.ref = "websocket" }

#Test Dependencies
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
