[versions]
opendcs = "7.0.11"

jetty = "9.4.53.v20231009"
jetty-jsp = "9.2.30.v20200428"
javax-servlet-jsp = "2.3.0"
jasper-runtime = "5.5.23"
#jetty = "9.0.0.v20130308"
logback = "1.3.14"
apache-tomcat = "9.0.84"
tomcat-embed = "9.0.84"
servlet-api = "3.1.0"
slf4j = "2.0.10"
jersey = "2.40"
postgresql = "42.7.1"
swagger = "2.2.20"
swagger-ui = "5.10.3"
glassfish-jaxb = "2.3.3"
websocket = "1.1"

#Test Dependencies
junit = "5.10.1"
mockito = "3.12.4"

[libraries]
opendcs = { module = "org.opendcs:opendcs", version.ref = "opendcs" }
apache-tomcat = { module = "org.apache.tomcat:tomcat-catalina", version.ref = "apache-tomcat"}
jetty-jsp = { module = "org.eclipse.jetty:jetty-jsp", version.ref = "jetty-jsp" }
jetty-plus = { module = "org.eclipse.jetty:jetty-plus", version.ref = "jetty" }
jetty-annotations = { module = "org.eclipse.jetty:jetty-annotations", version.ref = "jetty" }
jetty-server = { module = "org.eclipse.jetty:jetty-server", version.ref = "jetty" }
jetty-servlets = { module = "org.eclipse.jetty:jetty-servlets", version.ref = "jetty" }
jetty-servlet = { module = "org.eclipse.jetty:jetty-servlet", version.ref = "jetty" }
jetty-webapp = { module = "org.eclipse.jetty:jetty-webapp", version.ref = "jetty" }
jasper-runtime = { module = "tomcat:jasper-runtime", version.ref = "jasper-runtime" }
tomcat-embed = { module = "org.apache.tomcat.embed:tomcat-embed-jasper", version.ref = "tomcat-embed" }



javax-servlet-jsp = { module = "javax.servlet.jsp:javax.servlet.jsp-api", version.ref= "javax-servlet-jsp" }
servlet-api = { module = "javax.servlet:javax.servlet-api", version.ref = "servlet-api" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
jersey-client = { module = "org.glassfish.jersey.core:jersey-client", version.ref = "jersey" }
jersey-server = { module = "org.glassfish.jersey.core:jersey-server", version.ref = "jersey" }
json-jackson = { module = "org.glassfish.jersey.media:jersey-media-json-jackson", version.ref = "jersey" }
jersey-common = { module = "org.glassfish.jersey.core:jersey-common", version.ref = "jersey" }
jersey-container-servlet = { module = "org.glassfish.jersey.containers:jersey-container-servlet", version.ref = "jersey" }
jersey-hk2 = { module = "org.glassfish.jersey.inject:jersey-hk2", version.ref = "jersey" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
swagger-jaxrs2 = { module = "io.swagger.core.v3:swagger-jaxrs2", version.ref = "swagger" }
swagger-ui = { module = "org.webjars:swagger-ui", version.ref = "swagger-ui" }
jaxb-runtime = { module = "org.glassfish.jaxb:jaxb-runtime", version.ref = "glassfish-jaxb" }
websocket = { module = "javax.websocket:javax.websocket-api", version.ref = "websocket" }

#Test Dependencies
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
